// AUTO-GENERATED by scripts/watchlist-rs.mjs — DO NOT EDIT BY HAND.
// Refresh: node --env-file=.env.local scripts/watchlist-rs.mjs   (add --from-cache for formula-only reruns)
// PER-STOCK thrust/rs1m for every non-INDEX ticker on Valen's TradingView watchlist
// (src/watchlist-data.js), vs RSP (equal-weight benchmark) — the SAME formulas as the Group RS /
// Liquid Leaders table (scripts/group-rs.mjs): rs1m = PERCENTRANK.INC of the RS ratio (close÷RSP)
// in its own trailing 21 sessions ×100; thrust = RS Thrust Rate % = 0.6·RS1W + 0.4·rs1m +
// 0.1·(RS1W_t − RS1W_{t-3}), RS1W = the same PERCENTRANK on a trailing 7-session window, rounded
// half-up. Every number is bar-derived; failed fetches are kept as rows with thrust:null/rs1m:null.
// DeepVue stays the source of truth for single-stock RS and sector grouping.
export const WATCHLIST_RS = {
  "asof": "2026-08-04",
  "refreshed": "2026-08-05",
  "rows": [
    {
      "t": "SOXL",
      "thrust": 81,
      "rs1m": 35
    },
    {
      "t": "TQQQ",
      "thrust": 97,
      "rs1m": 75
    },
    {
      "t": "UAL",
      "thrust": 98,
      "rs1m": 95
    },
    {
      "t": "HPE",
      "thrust": 107,
      "rs1m": 100
    },
    {
      "t": "NAVN",
      "thrust": 82,
      "rs1m": 85
    },
    {
      "t": "CRWD",
      "thrust": 99,
      "rs1m": 90
    },
    {
      "t": "FTNT",
      "thrust": 96,
      "rs1m": 85
    },
    {
      "t": "DELL",
      "thrust": 105,
      "rs1m": 95
    },
    {
      "t": "NET",
      "thrust": 100,
      "rs1m": 100
    },
    {
      "t": "DDOG",
      "thrust": 100,
      "rs1m": 100
    },
    {
      "t": "PANW",
      "thrust": 103,
      "rs1m": 95
    },
    {
      "t": "SNOW",
      "thrust": 100,
      "rs1m": 100
    },
    {
      "t": "NTAP",
      "thrust": 100,
      "rs1m": 100
    },
    {
      "t": "MSFT",
      "thrust": 86,
      "rs1m": 95
    },
    {
      "t": "OKTA",
      "thrust": 84,
      "rs1m": 60
    },
    {
      "t": "GOOGL",
      "thrust": 88,
      "rs1m": 90
    },
    {
      "t": "GGLL",
      "thrust": 101,
      "rs1m": 95
    },
    {
      "t": "VSXY",
      "thrust": 31,
      "rs1m": 60
    },
    {
      "t": "VLO",
      "thrust": 33,
      "rs1m": 45
    },
    {
      "t": "DINO",
      "thrust": 4,
      "rs1m": 35
    },
    {
      "t": "AMZN",
      "thrust": 76,
      "rs1m": 90
    },
    {
      "t": "RNG",
      "thrust": 105,
      "rs1m": 100
    },
    {
      "t": "CHYM",
      "thrust": 100,
      "rs1m": 100
    },
    {
      "t": "OII",
      "thrust": 89,
      "rs1m": 90
    },
    {
      "t": "HPQ",
      "thrust": 90,
      "rs1m": 95
    },
    {
      "t": "GRND",
      "thrust": 88,
      "rs1m": 95
    },
    {
      "t": "KMX",
      "thrust": 7,
      "rs1m": 30
    },
    {
      "t": "KARO",
      "thrust": 10,
      "rs1m": 45
    },
    {
      "t": "RHI",
      "thrust": 98,
      "rs1m": 75
    },
    {
      "t": "ETON",
      "thrust": 43,
      "rs1m": 75
    },
    {
      "t": "AVGO",
      "thrust": 103,
      "rs1m": 100
    },
    {
      "t": "NVDA",
      "thrust": 91,
      "rs1m": 60
    },
    {
      "t": "DAVE",
      "thrust": 96,
      "rs1m": 65
    },
    {
      "t": "PTRN",
      "thrust": 35,
      "rs1m": 20
    },
    {
      "t": "CRSR",
      "thrust": 102,
      "rs1m": 100
    },
    {
      "t": "EVC",
      "thrust": 76,
      "rs1m": 70
    },
    {
      "t": "STX",
      "thrust": 56,
      "rs1m": 35
    },
    {
      "t": "NTNX",
      "thrust": 88,
      "rs1m": 95
    },
    {
      "t": "DLO",
      "thrust": 39,
      "rs1m": 60
    },
    {
      "t": "LLY",
      "thrust": 0,
      "rs1m": 0
    },
    {
      "t": "ORKA",
      "thrust": 73,
      "rs1m": 90
    },
    {
      "t": "CBRS",
      "thrust": 101,
      "rs1m": 95
    },
    {
      "t": "HUT",
      "thrust": 15,
      "rs1m": 20
    },
    {
      "t": "CIFR",
      "thrust": 13,
      "rs1m": 15
    },
    {
      "t": "FIG",
      "thrust": 103,
      "rs1m": 100
    },
    {
      "t": "ZS",
      "thrust": 103,
      "rs1m": 100
    },
    {
      "t": "TEAM",
      "thrust": 103,
      "rs1m": 100
    },
    {
      "t": "MDB",
      "thrust": 100,
      "rs1m": 100
    },
    {
      "t": "SAIL",
      "thrust": 86,
      "rs1m": 95
    },
    {
      "t": "GTLB",
      "thrust": 102,
      "rs1m": 100
    },
    {
      "t": "NOW",
      "thrust": 88,
      "rs1m": 95
    },
    {
      "t": "ADBE",
      "thrust": 88,
      "rs1m": 95
    },
    {
      "t": "BLZE",
      "thrust": 103,
      "rs1m": 100
    },
    {
      "t": "NEO",
      "thrust": 100,
      "rs1m": 100
    },
    {
      "t": "MANH",
      "thrust": 47,
      "rs1m": 80
    },
    {
      "t": "GH",
      "thrust": 60,
      "rs1m": 50
    },
    {
      "t": "PRCH",
      "thrust": 100,
      "rs1m": 100
    },
    {
      "t": "THC",
      "thrust": 35,
      "rs1m": 75
    },
    {
      "t": "AXTI",
      "thrust": 93,
      "rs1m": 95
    },
    {
      "t": "ANET",
      "thrust": 101,
      "rs1m": 90
    },
    {
      "t": "PLTR",
      "thrust": 108,
      "rs1m": 100
    },
    {
      "t": "SNDK",
      "thrust": 79,
      "rs1m": 35
    },
    {
      "t": "ALAB",
      "thrust": 89,
      "rs1m": 65
    },
    {
      "t": "SEZL",
      "thrust": 88,
      "rs1m": 50
    },
    {
      "t": "AMD",
      "thrust": 83,
      "rs1m": 40
    },
    {
      "t": "FSLY",
      "thrust": 100,
      "rs1m": 100
    },
    {
      "t": "HNGE",
      "thrust": 79,
      "rs1m": 35
    },
    {
      "t": "NBIS",
      "thrust": 101,
      "rs1m": 90
    },
    {
      "t": "GRPN",
      "thrust": 10,
      "rs1m": 45
    },
    {
      "t": "COMP",
      "thrust": 62,
      "rs1m": 50
    },
    {
      "t": "WDC",
      "thrust": 74,
      "rs1m": 55.00000000000001
    },
    {
      "t": "RVMD",
      "thrust": 76,
      "rs1m": 70
    },
    {
      "t": "TRVI",
      "thrust": 74,
      "rs1m": 65
    },
    {
      "t": "AVPT",
      "thrust": 82,
      "rs1m": 75
    },
    {
      "t": "PSNL",
      "thrust": 81,
      "rs1m": 45
    },
    {
      "t": "NTRA",
      "thrust": 66,
      "rs1m": 45
    },
    {
      "t": "MRVI",
      "thrust": 5,
      "rs1m": 20
    },
    {
      "t": "OSCR",
      "thrust": 12,
      "rs1m": 25
    },
    {
      "t": "XERS",
      "thrust": -7,
      "rs1m": 0
    },
    {
      "t": "TGTX",
      "thrust": 10,
      "rs1m": 5
    }
  ]
};
export default WATCHLIST_RS;
